### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by tom99763** [BIT-DA/BCDM#4]
In segmentation task, you uses deeplabv2 as your architecture, but I don't see CRF.

**Comment by BinhuiXie** [comment]
Hi@tom99763,

Thx for your attention. Our work only uses the DeepLabv2 backbone with ``dilated convolution`` and ``ASPP`` to obtain the final output. As for ``fully connected CRFs``, in the original paper, the authors use it as a post-processing to refine the prediction results, which is not applied in domain adaptive semantic segmentation.

**Comment by tom99763** [comment]
> Hi@tom99763,
> 
> Thx for your attention. Our work only uses the DeepLabv2 backbone with `dilated convolution` and `ASPP` to obtain the final output. As for `fully connected CRFs`, in the original paper, the authors use it as a post-processing to refine the prediction results, which is not applied in domain adaptive semantic segmentation.

Thank you for response.
BTW, I look your picture and guess that person is Allen Iverson, but is Lebron.

**Comment by BinhuiXie** [comment]
Yup! I'm closing this.  Pls feel free to ask if you have further questions.
